# Generated by Django 5.1.1 on 2024-12-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_salaryrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('user', 'check_in')},
        ),
    ]
