# Generated by Django 5.1.1 on 2024-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='jar_price_at_delivery',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of each jar sold during this delivery', max_digits=6),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sold_new_jars',
            field=models.IntegerField(default=0, help_text='Number of new jars sold during delivery'),
        ),
        migrations.AddField(
            model_name='jar',
            name='jar_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per jar if sold', max_digits=6),
        ),
        migrations.AddField(
            model_name='jar',
            name='sold_jars',
            field=models.IntegerField(default=0, help_text='Number of jars sold'),
        ),
    ]
