# Generated by Django 5.1.1 on 2024-10-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_delivery_jar_price_at_delivery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_jars_delivered', models.IntegerField()),
                ('jar_type', models.CharField(choices=[('P', 'Premium'), ('N', 'Normal')], max_length=1)),
                ('regular_delivery_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('new_jar_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collectable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount received from the customer', max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for the bill, if any', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.customer')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='product.delivery')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.vehicle')),
            ],
        ),
    ]
