# Generated by Django 5.1.1 on 2024-12-06 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_delivery_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expense_type', models.CharField(choices=[('DAILY', 'Daily Expense'), ('MISCELLANEOUS', 'Miscellaneous'), ('VENDOR', 'Vendor'), ('SALARY', 'Salary')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the expense', null=True)),
                ('vendor_name', models.CharField(blank=True, help_text='Vendor name if expense type is vendor', max_length=255, null=True)),
                ('vendor_invoice_number', models.CharField(blank=True, help_text='Invoice number for the vendor expense', max_length=255, null=True)),
                ('miscellaneous_details', models.TextField(blank=True, help_text='Details for miscellaneous expenses', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Only for salary-related expenses', limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Expense',
                'verbose_name_plural': 'Monthly Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
