# Generated by Django 5.1.1 on 2024-12-23 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_monthlyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('jar_in', models.PositiveIntegerField(default=0, help_text='Number of jars coming in.')),
                ('jar_out', models.PositiveIntegerField(default=0, help_text='Number of jars going out.')),
                ('notes', models.TextField(blank=True, help_text='Additional info about this record.', null=True)),
            ],
        ),
    ]
