# Generated by Django 5.1.1 on 2024-12-23 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_jarinout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='collectable_amount',
            new_name='amount_received_by_driver',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='total_cost',
            new_name='receivable_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='amount_received',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='jar_type',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='new_jar_cost',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='regular_delivery_cost',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_jars_delivered',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='bill',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who recorded this bill.', limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='online_method',
            field=models.CharField(blank=True, choices=[('mobile_banking', 'Mobile Banking'), ('digital_wallet', 'Digital Wallet')], help_text='Mobile Banking or Digital Wallet (required if Online).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_category',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', help_text='Main category: Cash or Online.', max_length=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
