# Generated by Django 5.1.1 on 2024-12-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_collectable_amount_bill_amount_received_by_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='added_by',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Driver who received or handled the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.driver'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='online_method',
            field=models.CharField(blank=True, choices=[('mobile_banking', 'Mobile Banking'), ('digital_wallet', 'Digital Wallet')], help_text='Mobile Banking or Digital Wallet (required if Online)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_category',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', help_text='Cash or Online', max_length=10),
        ),
    ]
