# Generated by Django 5.1.1 on 2024-12-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_bill_added_by_bill_customer_bill_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='product.delivery'),
        ),
    ]
