# Generated by Django 5.1.1 on 2024-12-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_bill_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='driver',
        ),
        migrations.AlterField(
            model_name='bill',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='product.delivery'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='online_method',
            field=models.CharField(blank=True, choices=[('mobile_banking', 'Mobile Banking'), ('digital_wallet', 'Digital Wallet')], help_text='Required if payment_category = Online', max_length=20, null=True),
        ),
    ]
