# Generated by Django 5.1.1 on 2024-12-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_bill_customer_remove_bill_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JarCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_bora', models.PositiveIntegerField(help_text='Number of boras of jar caps currently in stock.')),
                ('price_per_bora', models.DecimalField(decimal_places=2, help_text='Price per bora of jar caps.', max_digits=8)),
                ('date_brought', models.DateField(default=datetime.datetime.now, help_text='Date when these jar caps were brought in.')),
            ],
        ),
    ]
