# Generated by Django 5.1.1 on 2024-12-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_jarcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarcap',
            name='usage_date',
            field=models.DateField(blank=True, help_text='Date when jar caps were last used (set 1 day ahead).', null=True),
        ),
    ]
