# Generated by Django 5.1.1 on 2024-12-25 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='vendor_invoice_number',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product associated with the expense (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='product.product'),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor associated with the expense (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='product.vendor'),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='expense_type',
            field=models.CharField(choices=[('DAILY', 'Daily Expense'), ('MISCELLANEOUS', 'Miscellaneous'), ('VENDOR', 'Vendor')], max_length=20),
        ),
    ]
