# Generated by Django 5.1.1 on 2024-12-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_monthlyexpense_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('registration_number', models.IntegerField(max_length=20)),
                ('contact_number', models.IntegerField(max_length=20)),
                ('address', models.CharField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
            ],
        ),
    ]
