# Generated by Django 5.1.1 on 2024-12-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_creditmarket_filler'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarinout',
            name='fillers',
            field=models.ForeignKey(blank=True, help_text='Contact person filling the jars.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.filler'),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='half_cap',
            field=models.PositiveIntegerField(default=0, help_text='Number of jars with half caps.'),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='leak',
            field=models.PositiveIntegerField(default=0, help_text='Number of jars with leaks.'),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='name',
            field=models.CharField(blank=True, help_text='Name associated with the record.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='return_jar',
            field=models.PositiveIntegerField(default=0, help_text='Number of jars returned.'),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of the transaction.', null=True),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle number used for transportation.', max_length=20, null=True),
        ),
    ]
