# Generated by Django 5.1.1 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_jarinout_fillers_jarinout_half_cap_jarinout_leak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filler',
            name='number',
            field=models.CharField(),
        ),
    ]
