# Generated by Django 5.1.1 on 2024-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_filler_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmarket',
            name='contact_number',
            field=models.CharField(),
        ),
    ]
