# Generated by Django 5.1.1 on 2024-12-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_creditmarket_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmarket',
            name='registration_number',
            field=models.IntegerField(),
        ),
    ]
