# Generated by Django 5.1.1 on 2025-01-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_creditmarket_registration_number'),
    ]

    operations = [
        # Step 1: Add a new column with the target type (DateTimeField)
        migrations.AddField(
            model_name='jarinout',
            name='new_time',
            field=models.DateTimeField(blank=True, null=True, help_text='Datetime of the transaction.'),
        ),
        # Step 2: Copy and convert the data from the old field to the new one
        migrations.RunSQL(
            sql="""
                UPDATE product_jarinout 
                SET new_time = now()::date + time;
            """,
            reverse_sql="""
                UPDATE product_jarinout 
                SET time = new_time::time;
            """,
        ),
        # Step 3: Remove the old column
        migrations.RemoveField(
            model_name='jarinout',
            name='time',
        ),
        # Step 4: Rename the new column to the original column name
        migrations.RenameField(
            model_name='jarinout',
            old_name='new_time',
            new_name='time',
        ),
    ]