# Generated by Django 5.1.1 on 2025-01-06 18:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_jarinout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarinout',
            name='time',
            field=models.TimeField(blank=True, help_text='Time of the transaction.', null=True),
        ),
        migrations.CreateModel(
            name='FillerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.TextField(help_text='Details about the transaction.')),
                ('amount_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('filler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='product.filler')),
            ],
        ),
    ]
