# Generated by Django 5.1.1 on 2025-01-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_alter_jarinout_time_fillerledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarinout',
            name='time',
        ),
        migrations.AddField(
            model_name='jarinout',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the transaction.', null=True),
        ),
        migrations.AlterField(
            model_name='filler',
            name='contact_person',
            field=models.CharField(help_text='Name of the contact person for the filler.', max_length=100),
        ),
        migrations.AlterField(
            model_name='filler',
            name='number',
            field=models.CharField(help_text='Contact number.', max_length=15),
        ),
        migrations.AlterField(
            model_name='filler',
            name='vehicle_number',
            field=models.CharField(help_text='Vehicle number used by the filler.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='fillers',
            field=models.ForeignKey(blank=True, help_text='Contact person filling the jars.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jar_records', to='product.filler'),
        ),
    ]
