# Generated by Django 5.1.1 on 2025-01-06 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0025_rename_name_jarinout_driver_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="date",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="delivered_count",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="jar_price_at_delivery",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="jar_type",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="sold_new_jars",
        ),
        migrations.AddField(
            model_name="customer",
            name="is_monthly_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delivery",
            name="total_jars",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="driver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="half_caps_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="leak_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="returned_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="DeliveryCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price_per_jar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.customer",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_deliveries",
                        to="product.delivery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("trip_number", models.PositiveIntegerField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="delivery",
            name="trip",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="product.trip",
            ),
            preserve_default=False,
        ),
    ]
