# Generated by Django 5.1.1 on 2025-01-06 19:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_jarinout_time_jarinout_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fillerledger',
            name='description',
        ),
        migrations.AddField(
            model_name='fillerledger',
            name='jar_in_out',
            field=models.ForeignKey(blank=True, help_text='The Jar In/Out record associated with this ledger entry.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_records', to='product.jarinout'),
        ),
        migrations.AddField(
            model_name='fillerledger',
            name='remarks',
            field=models.TextField(blank=True, help_text='Remarks or additional details about this ledger entry.', null=True),
        ),
        migrations.AlterField(
            model_name='fillerledger',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount still due.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fillerledger',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from the filler.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fillerledger',
            name='filler',
            field=models.ForeignKey(help_text='The filler associated with this ledger entry.', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='product.filler'),
        ),
    ]
