# Generated by Django 5.1.1 on 2025-01-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_remove_delivery_customer_remove_delivery_date_and_more'),
        ('product', '0027_remove_fillerledger_description_and_more'),
    ]

    operations = [
    ]
