# Generated by Django 5.1.1 on 2025-01-08 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_merge_20250107_1556'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_monthly_customer',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='driver',
        ),
        migrations.AddField(
            model_name='jarinout',
            name='name',
            field=models.CharField(blank=True, help_text='Name associated with the record.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='time',
            field=models.DateTimeField(blank=True, help_text='Datetime of the transaction.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('monthly', 'Monthly Base'), ('in_hand', 'In-Hand')], max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverycustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='product.customer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('driver', 'date', 'trip_number')},
        ),
    ]
