# Generated by Django 5.1.1 on 2025-01-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_jarinout_driver_name_remove_jarinout_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarinout',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
