# Generated by Django 5.1.1 on 2025-01-14 15:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_jarinout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jarinout',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Remaining due amount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='receivable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Total receivable amount for the jars.', max_digits=10),
        ),
        migrations.AddField(
            model_name='jarinout',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received from the filler.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='jar_out',
            field=models.PositiveIntegerField(default=0, help_text='Number of jars going out (calculated).'),
        ),
    ]
