# Generated by Django 5.1.1 on 2025-01-14 15:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_jarinout_due_amount_jarinout_receivable_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillerledger',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative due amount for the filler.', max_digits=10),
        ),
    ]
