# Generated by Django 5.1.1 on 2025-01-14 15:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_fillerledger_amount_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jarinout',
            name='time',
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Remaining due amount after this transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='jar_out',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of jars going out (calculated).'),
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='receivable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount to be collected for this transaction.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='jarinout',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount received for this transaction.', max_digits=10),
        ),
    ]
