# Generated by Django 5.1.1 on 2025-01-14 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_remove_jarinout_time_alter_jarinout_due_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarinout',
            name='receivable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bill Amount to be collected for this transaction.', max_digits=10),
        ),
    ]
