# Generated by Django 5.1.1 on 2025-01-14 17:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_jarinout_receivable_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycustomer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='deliverycustomer',
            name='delivery',
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='half_caps_count',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='leak_count',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='returned_count',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='total_jars',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='ONGOING', max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='WaterProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_type', models.CharField(choices=[('JAR', 'Jar'), ('BOTTLE', 'Bottle')], max_length=10)),
                ('quality', models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium')], max_length=10)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('water_type', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='InventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaks', models.PositiveIntegerField(default=0)),
                ('returns', models.PositiveIntegerField(default=0)),
                ('half_caps', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='product.delivery')),
                ('water_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.waterproduct')),
            ],
            options={
                'unique_together': {('delivery', 'water_product')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_items', to='product.delivery')),
                ('monthly_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.monthlycustomer')),
                ('water_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.waterproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='product.delivery')),
                ('water_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.waterproduct')),
            ],
            options={
                'unique_together': {('delivery', 'water_product')},
            },
        ),
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('monthly_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.monthlycustomer')),
                ('water_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.waterproduct')),
            ],
            options={
                'unique_together': {('monthly_customer', 'water_product', 'effective_from')},
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='DeliveryCustomer',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
